[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "KarmaReplicant"
name = "GupRankings"
versionNumber = "1.0.1"
description = "A mod that adds a Leaderboard based on different statistics to the objective panel."
websiteUrl = "https://github.com/cjcocokrisp/GupRankings"
containsNsfwContent = false

[package.dependencies]
bbepis-BepInExPack = "5.*"
Rune580-Risk_Of_Options = "2.8.2"
tristanmcpherson-R2API = "5.0.5"
RiskofThunder-R2API_Networking = "1.0.2"

[build]
icon = "./icons/icon.png"
readme = "../README.md"
outdir = "../dist"

[[build.copy]]
source = "../GupRankings/bin/Release/netstandard2.1/GupRankings.dll"
target = "plugins/GupRankings/"

[[build.copy]]
source = "../GupRankings/bin/Release/netstandard2.1/GupRankings.pdb"
target = "plugins/GupRankings/"

[[build.copy]]
source = "./icons/icon.png"
target = "plugins/GupRankings/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "./"

[[build.copy]]
source = "../LICENSE"
target = "./"

[publish]
communities = [ "riskofrain2" ]

[publish.categories]
riskofrain2 = [ "mods", "client-side", "server-side", "tweaks" ]