name: Build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore project
        run: | 
          dotnet restore
          dotnet tool restore

      - name: Install Thunderstore CLI
        run: dotnet tool install -g tcli

      - name: Build project
        run: dotnet build -c Release

      - name: Package project
        run: tcli build --config-path ../Thunderstore/thunderstore.toml

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ../dist/*.zip
